### ISSUE TITLE
Spurious “Macro syntax error” for /en-US/docs/Web/HTML/Element

### ISSUE THREAD

**Issue by sideshowbarker** [Elchi3/mdn-doc-tests#229] opened 2017-01-01 19:57 UTC
https://developer.mozilla.org/en-US/docs/Web/HTML/Element$edit causes the documentation tester to emit 8 “Macro syntax error” messages: 4 “Macro is missing a closing curly brace” errors and 4 “String parameter is not quoted correctly” errors.

But is seems there are actually no macro syntax errors in the source of that article. Instead, the cases the documentation tester is flagging seem to be valid ones that look like this:

```
<p>{{HTMLRefTable({"include":["HTML embedded content"], "exclude":["multimedia"]})}}</p>
```

I guess the macro parser in the documentation tester is not dealing correctly with the nesting or the bracketed array syntax.

**Comment by Elchi3** [comment] 2017-07-13 13:03
Duplicate of #139

**Closed as completed by Elchi3** 2017-07-13 13:03 UTC
